### ISSUE TITLE
Obvious issues with my usage?

### ISSUE THREAD

**Issue by arran4** [DenverCoder1/doxygen-github-pages-action#10]
Is there anything obviously wrong with my usage here:
https://github.com/DMJC/Linwarrior3D/runs/6237704319?check_suite_focus=true

https://github.com/DMJC/Linwarrior3D/blob/main/.github/workflows/ghpdoxy.yaml

?

**Comment by DenverCoder1** [comment]
The error says `"Doxyfile not found and no input file specified!"`

Maybe try renaming your doxygen config file to `Doxyfile`?

**Comment by arran4** [comment]
Is it possible to overwrite / specify our own?

**Comment by DenverCoder1** [comment]
Currently, it assumes the default name will be used.

#11 should allow you to change it from the default. Let me know what you think.

**Comment by arran4** [comment]
Looks good. Having the option there also in effect documents the behavior of the default. I approve.
