### ISSUE TITLE
Doesn't create folder if it doesn't exist

### ISSUE THREAD

**Issue by arran4** [DenverCoder1/doxygen-github-pages-action#12]
I needed to add:
```
      - name: mkdir
        run: mkdir -p docs/html
```
Above to get it to work.

Actually that failed b/c of a tree change or context change, I needed to add a .gitkeep to the folder to get past that point. Perhaps a "create-folder-if-not-exist' option which defaults to true?

**Comment by DenverCoder1** [comment]
This should happen automatically when you run `doxygen`.

If it doesn't, make sure the Output Directory in your configuration matches the folder configured in the action.

**Comment by arran4** [comment]
Ahhh..
