### ISSUE TITLE
idea: graphviz support

### ISSUE THREAD

**Issue by PF94** [DenverCoder1/doxygen-github-pages-action#14]
the yml file does not appear to install graphviz, meaning that attempting to use graphviz will most likely error out.

**Comment by DenverCoder1** [comment]
Have you tried adding a step to install it before starting the doxygen workflow?

I have not tested this, but that could be a simple solution if it works.

Otherwise, maybe it could be interesting to have an optional parameter for additional dependencies it should install.

**Comment by PF94** [comment]
> Have you tried adding a step to install it before starting the doxygen workflow?
> 
> I have not tested this, but that could be a simple solution if it works.

are there any ways on how to do that?

**Comment by DenverCoder1** [comment]
If it is a ubuntu package, in the steps you can try to add
```
    - name: Install graphviz
      run: sudo apt-get install graphviz -y
      shell: bash
```

**Comment by DenverCoder1** [comment]
If it is a ubuntu package, in the steps you can try to add
```
    - name: Install graphviz
      run: sudo apt-get install graphviz -y
      shell: bash
```

You can see the yml file for an example

**Comment by antonioiuliano2** [comment]
Hello,

First, thank you very much for this very useful GitHub Action!

I also confirm that the current version does not support graphs. 
In particular, it complains about "dot" command missing.

Your suggested solution to install graphviz worked for me.
Thank you very much.
