### ISSUE TITLE
There is nothing to commit; Exitting early

### ISSUE THREAD

**Issue by schkwve** [DenverCoder1/doxygen-github-pages-action#28]
Hi,
I've tried to use this action for my project, but was met with the following message at the end of the action run:
```
There is nothing to commit. Exiting early… 📭
```
Unfortunately I didn't notice any error beforehand; everything seems to go smoothly up until the point where it tries to commit the documentation to the `gh-pages` branch.

[You can see the action log here](https://github.com/schkwve/nighterm-extended/actions/runs/8599125372/job/23561358609).

Could you maybe look at the logs and see what's wrong?

--
Thanks a lot,
Jozef

**Comment by WeileiZeng** [comment]
It looks like this issue has been resolved.

**Comment by schkwve** [comment]
Right, absolutely forgot I've opened this issue. The issue was in poor settings of GitHub pages and incorrect setting of doxygen.yml.
