### ISSUE TITLE
Question: gh-pages branch

### ISSUE THREAD

**Issue by hasenradball** [DenverCoder1/doxygen-github-pages-action#33]
Hi,

I also on the way to deploy via doxygen the github page.
Question regarding the branch `gh-pages`.
Is it a copy of the actual main, or does it only contain the docs folder to serve the html stuff?

**Comment by DenverCoder1** [comment]
It will be a separately maintained branch that just has the pages for the static github pages site.

It should get created automatically if you set up your GitHub pages site in the repo settings to point to the gh-pages branch.
